-- MySQL Script generated by MySQL Workbench
-- Sat Apr  9 17:25:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema datamart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datamart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datamart` ;
USE `datamart` ;

-- -----------------------------------------------------
-- Table `datamart`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart`.`Pelicula` (
  `idPelicula` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `año` INT NOT NULL,
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart`.`Vendedor` (
  `idVendedor` INT NOT NULL,
  `nombre` VARCHAR(91) NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart`.`Fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart`.`Fecha` (
  `idFecha` INT NOT NULL,
  `dia` INT NULL,
  `mes` INT NULL,
  `año` INT NULL,
  `fecha` DATE NULL,
  `diaSemana` VARCHAR(45) NULL,
  PRIMARY KEY (`idFecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart`.`Tienda` (
  `idTienda` INT NOT NULL,
  `direccion` TEXT NOT NULL,
  PRIMARY KEY (`idTienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(91) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datamart`.`Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datamart`.`Alquiler` (
  `idPelicula` INT NOT NULL,
  `idTiempo` INT NOT NULL,
  `idTienda` INT NOT NULL,
  `idVendedor` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `monto` FLOAT NOT NULL,
  PRIMARY KEY (`idPelicula`, `idTiempo`, `idTienda`, `idVendedor`, `idCliente`),
  INDEX `fk_Alquiler_Pelicula1_idx` (`idPelicula` ASC) VISIBLE,
  INDEX `fk_Alquiler_Tiempo1_idx` (`idTiempo` ASC) VISIBLE,
  INDEX `fk_Alquiler_Tienda1_idx` (`idTienda` ASC) VISIBLE,
  INDEX `fk_Alquiler_Vendedor1_idx` (`idVendedor` ASC) VISIBLE,
  INDEX `fk_Alquiler_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Alquiler_Pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `datamart`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Tiempo1`
    FOREIGN KEY (`idTiempo`)
    REFERENCES `datamart`.`Fecha` (`idFecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Tienda1`
    FOREIGN KEY (`idTienda`)
    REFERENCES `datamart`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Vendedor1`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `datamart`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `datamart`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
